{% set data = load_setup_py_data() %}

package:
  name: openalea.plantgl
  version: {{ data.get('version') }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  number: 1
  preserve_egg_dir: True

requirements:
  host:
      - python {{PY_VER}}
      - setuptools
      - numpy
      - qt
      - pyqt
      - libpng
      - zlib
      - eigen
      - cgal-cpp
      - qhull
      - ann
      - boost                              # [unix]
      - boost <1.74                        # [win] # v1.74 has a bug on windows.
      - expat                              # [linux]
      - libxcb                             # [linux]
      - pthread-stubs                      # [linux]
      - {{ cdt('mesa-libgl-devel') }}      # [linux]
      - libglu                            # [linux]
      - xorg-libxfixes                    # [linux]
          
  build:
      - python {{PY_VER}}                 
      - binutils_impl_linux-64            # [linux]
      - {{ compiler('cxx') }}
      - bison                             # [unix]
      - flex                              # [unix]
      - m2-bison                          # [win]
      - m2-flex                           # [win]
      - menuinst                          # [win]
      - cmake
      - pkg-config                        # [linux]
      - make                              # [unix]
      - {{ cdt('mesa-libgl-devel') }}     # [linux]
      - {{ cdt('mesa-dri-drivers') }}     # [linux]
      - {{ cdt('libxext') }}              # [linux]
      - {{ cdt('libselinux') }}           # [linux]
      - {{ cdt('libxdamage') }}           # [linux]
      - {{ cdt('libxfixes') }}            # [linux]
      - {{ cdt('libxxf86vm') }}           # [linux]
      - {{ cdt('libxcb') }}               # [linux]
      - {{ cdt('expat-devel') }}          # [linux]

  run:
      - python {{PY_VER}}
      - setuptools
      - ipython
      - {{ pin_compatible('numpy') }}
      - {{ pin_compatible('boost',    max_pin='x.x.x') }} 
      - {{ pin_compatible('qhull',    max_pin='x.x') }} 
      - {{ pin_compatible('eigen',    max_pin='x.x') }} 
      - {{ pin_compatible('cgal-cpp', max_pin='x.x') }} 
      - {{ pin_compatible('ann',      max_pin='x.x') }} 
      - {{ pin_compatible('qt',       max_pin='x.x') }} 
      - {{ pin_compatible('libpng',   max_pin='x.x') }} 
      - {{ pin_compatible('zlib',     max_pin='x.x') }} 
      - pyqt
      - pyopengl
      - pyqglviewer
      - xorg-libxfixes                     # [linux]
      - libglu                             # [linux]

test:
   requires:
     - pytest
     - matplotlib-base
     - pandas
   imports:
     - openalea.plantgl
     - openalea.plantgl.all
   source_files:
     - test/**
     - share/**
   commands:
     - cd test
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest  # [unix]
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest --ignore=test_shared_data.py  # [win]

