{% set data = load_setup_py_data() %}

package:
  name: openalea.plantgl
  version: {{ data.get('version') }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  number: 1
  preserve_egg_dir: True

requirements:
  host:
      - python {{PY_VER}}
      - setuptools
      - pip
      - numpy
      - eigen
      - cgal-cpp
      - qhull
      - ann
      - qt
      - pyqt
      - boost<=1.71 # boost module of conda-forge install boost.python and dependency boost-cpp for the cpp libs.
      - libpng
      - zlib
      - libglu                            # [linux]
      - xorg-libxfixes                    # [linux]

      # https://github.com/conda-forge/glew-feedstock/issues/9#issuecomment-450441917
  build:
      - python {{PY_VER}}
      - {{ compiler('cxx') }}
      - bison                             # [unix]
      - flex                              # [unix]
      - m2-bison                          # [win]
      - m2-flex                           # [win]
      - menuinst                          # [win]
      - {{ compiler("c") }}
      - {{ compiler("cxx") }}
      - cmake
      - pkg-config                         # [linux]
      - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
      - {{ cdt('libx11-devel') }}          # [linux]
      - {{ cdt('libxcb') }}                # [linux]
      - {{ cdt('libXfixes') }}             # [linux]
      - {{ cdt('libXxf86vm') }}            # [linux]
      - {{ cdt('libxext-devel') }}         # [linux]
      - {{ cdt('libxrender-devel') }}      # [linux]
      - {{ cdt('mesa-libgl-devel') }}      # [linux]
      - {{ cdt('mesa-dri-drivers') }}      # [linux]
      - {{ cdt('libselinux') }}            # [linux]
      - {{ cdt('libXdamage') }}            # [linux]
      - {{ cdt('libXau') }}                # [linux]
      - {{ cdt('expat-devel') }}           # [linux]
  run:
      - python {{PY_VER}}
      - setuptools
      - ipython
      - pyqt
      - pyopengl
      - pyqglviewer
      - xorg-libxfixes                     # [linux]
      - libglu                             # [linux]
      - expat                             # [linux]

test:
   requires:
     - pytest
     - matplotlib-base
     - pandas
     - boost<=1.71
     - eigen
     - cgal-cpp
     - qhull
     - ann
   imports:
     - openalea.plantgl
     - openalea.plantgl.all
   source_files:
     - test/**
     - share/**
   commands:
     - cd test
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest  # [unix]
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest --ignore=test_shared_data.py  # [win]
