{% set data = load_setup_py_data() %}

package:
  name: openalea.plantgl
  version: {{ data.get('version') }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  number: 1
  preserve_egg_dir: True

requirements:
  host:
      - python {{PY_VER}}
      - setuptools
      - pip
      - numpy
      - eigen
      - cgal-cpp
      - qhull
      - ann
      - qt 
      - pyqt
      - boost # boost module of conda-forge install boost.python and dependency boost-cpp for the cpp libs.
      - libpng
      - zlib
      - libglu                            # [linux]
      - xorg-libxfixes                    # [linux]
          
  build:
      - python {{PY_VER}}                 # [win]
      - binutils_impl_linux-64<2.31.0     # [linux]
      - {{ compiler('cxx') }}
      - bison                             # [unix]
      - flex                              # [unix]
      - m2-bison                          # [win]
      - m2-flex                           # [win]
      - menuinst                          # [win]
      - cmake >=3.12.0
      - pkg-config                        # [linux]
      - make                              # [unix]
      - {{ cdt('mesa-libgl-devel') }}      # [linux]
      - {{ cdt('mesa-dri-drivers') }}      # [linux]
      - {{ cdt('libselinux') }}            # [linux]
      - {{ cdt('libxdamage') }}            # [linux]
      - {{ cdt('libxxf86vm') }}            # [linux]
      - {{ cdt('libxext') }}               # [linux]
      - libglu                             # [linux]
  run:
      - python {{PY_VER}}
      - setuptools
      - ipython
      - {{ pin_compatible('numpy') }}
      - {{ pin_compatible('boost',    max_pin='x.x.x') }} 
      - {{ pin_compatible('qhull',    max_pin='x.x') }} 
      - {{ pin_compatible('eigen',    max_pin='x.x') }} 
      - {{ pin_compatible('cgal-cpp', max_pin='x.x') }} 
      - {{ pin_compatible('ann',      max_pin='x.x') }} 
      - {{ pin_compatible('qt',       max_pin='x.x') }} 
      - {{ pin_compatible('libpng',   max_pin='x.x') }} 
      - {{ pin_compatible('zlib',     max_pin='x.x') }} 
      - pyqt
      - pyopengl
      - pyqglviewer
      - xorg-libxfixes                     # [linux]
      - libglu                             # [linux]

test:
   requires:
     - pytest
     - matplotlib-base
     - pandas
   imports:
     - openalea.plantgl
     - openalea.plantgl.all
   source_files:
     - test/**
     - share/**
   commands:
     - cd test
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest  # [unix]
     - pytest -v --ignore=tofix --ignore=ui --ignore=oatest --ignore=test_shared_data.py  # [win]

