# Include Directory
if (DEFINED ENV{CONDA_PREFIX})
    find_path(DRACO_INCLUDE_DIR "draco"  $ENV{CONDA_PREFIX}/include)
else ()
    find_path(DRACO_INCLUDE_DIR "draco" $ENV{PATH} PATHS)
endif()

# Library Directory
if (WIN32)
    if (DEFINED ENV{CONDA_PREFIX})
        find_library(DRACO_LIBRARY NAMES "draco" $ENV{CONDA_PREFIX}/lib)
    else()
        find_library(DRACO_LIBRARY NAMES "draco" PATHS $ENV{PATH} )
    endif()
else()
    if (DEFINED ENV{CONDA_PREFIX})
        find_library(DRACO_LIBRARY NAMES "draco" "libdraco" $ENV{CONDA_PREFIX}/lib)
    else()
        find_library(DRACO_LIBRARY NAMES "draco" "libdraco" PATHS $ENV{PATH})
    endif()
endif()

if (DRACO_INCLUDE_DIR AND DRACO_LIBRARY)
    set(DRACO_INCLUDE_DIRS ${DRACO_INCLUDE_DIR})
    set(DRACO_LIBRARIES ${DRACO_LIBRARY})
    include_directories(${DRACO_INCLUDE_DIRS})
    message(STATUS "Found draco: ${DRACO_LIBRARY}")
else()
    message(SEND_ERROR "Unable to find draco library.")
endif()
